name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/web-backend-node
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .

      - name: Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/web-backend-node
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p ~/website/web-backend-node
            mkdir -p ~/website/web-backend-node/.key
            cd ~/website/web-backend-node

            cat > .env.production << 'EOF'
            ${{ secrets.PROD }}
            EOF

            echo "${{ secrets.JWT_PRIVATE_KEY }}" | tr -d '\r' > .key/private.key
            echo "${{ secrets.JWT_PUBLIC_KEY }}" | tr -d '\r' > .key/public.key

            cd ~/website/

            docker compose pull
            docker compose up -d
            docker image prune -f
