name: cd

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/web-backend-node
          docker build -t $IMAGE:latest -t $IMAGE:${{ github.sha }} .

      - name: Push Image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/web-backend-node
          docker push $IMAGE:latest
          docker push $IMAGE:${{ github.sha }}
